import { StyleSheet } from "react-native";
import { colors, shadows } from "@/common/common-constants/ThemeConstants";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surface,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  addShiftButtonRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    flexShrink: 0,
  },
  addShiftButton: {
    display: "none", // +ボタンのみ非表示
    backgroundColor: "rgba(33, 150, 243, 0.9)",
    borderRadius: 13,
    padding: 5,
    width: 26,
    height: 29,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: colors.surface,
    width: "30%",
    maxHeight: "100%",
    borderRadius: 10,
    padding: 5,
    ...shadows.modal,
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 4,
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: 9,
    color: colors.text.secondary,
    marginBottom: 3,
    textAlign: "center",
  },
  timeInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 3,
  },
  timeInputGroup: {
    flex: 1,
  },
  timeInputLabel: {
    fontSize: 9,
    color: colors.text.secondary,
    marginBottom: 3,
  },
  timeInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 3,
    padding: 4,
    fontSize: 10,
  },
  timeInputSeparator: {
    marginHorizontal: 5,
    fontSize: 11,
    color: colors.text.secondary,
  },
  formGroup: {
    marginBottom: 4,
  },
  formLabel: {
    fontSize: 9,
    color: colors.text.secondary,
    marginBottom: 3,
  },
  pickerContainer: {
    marginBottom: 5,
    backgroundColor: "transparent",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalButton: {
    flex: 1,
    paddingVertical: 5,
    borderRadius: 3,
    alignItems: "center",
  },
  cancelButton: {
    marginRight: 5,
    backgroundColor: colors.surfaceElevated,
  },
  cancelButtonText: {
    color: colors.text.secondary,
    fontWeight: "bold",
  },
  saveButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  headerRow: {
    flexDirection: "row",
    backgroundColor: colors.surfaceElevated,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    elevation: 0,
    height: 29,
    alignItems: "center",
  },
  headerRightButtons: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 8,
    gap: 5,
  },
  headerButton: {
    backgroundColor: colors.primary,
    borderRadius: 6,
    paddingHorizontal: 13,
    paddingVertical: 6,
    marginLeft: 5,
    height: 28,
    minWidth: 52,
    justifyContent: "center",
    alignItems: "center",
    elevation: 0,
  },
  headerButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 13,
    letterSpacing: 0.3,
  },
  headerDateCell: {
    padding: 5,
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: colors.border,
  },
  headerGanttCell: {
    flexDirection: "row",
    position: "relative",
    borderRightWidth: 1,
    borderRightColor: colors.border,
    height: 29,
  },
  headerInfoCell: {
    padding: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  headerText: {
    fontWeight: "bold",
    fontSize: 10,
  },
  timeLabel: {
    fontSize: 12,
    textAlign: "center",
    fontWeight: "bold",
    color: colors.text.primary,
    paddingTop: 8,
  },
  monthSelector: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    minHeight: 48,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  monthNavigator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  monthNavButton: {
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  monthNavButtonText: {
    fontSize: 18,
    fontWeight: "500",
    color: colors.primary,
  },
  monthButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
  },
  monthText: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.text.primary,
  },
  content: {
    flex: 1,
  },
  shiftRow: {
    flexDirection: "row",
    minHeight: 44,
    height: 48,
  },
  dateCell: {
    padding: 4,
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: colors.border,
    backgroundColor: colors.surface,
  },
  dateDayText: {
    fontSize: 16,
    fontWeight: "bold",
  },
  dateWeekText: {
    fontSize: 11,
    fontWeight: "500",
  },
  ganttCell: {
    position: "relative",
    height: 46,
    borderRightWidth: 1,
    borderRightColor: colors.border,
    overflow: "hidden",
  },
  ganttBgRow: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
  },
  ganttBgCell: {
    height: "100%",
    borderRightColor: colors.border,
  },
  classTimeCell: {
    backgroundColor: "rgba(180, 180, 180, 0.15)",
  },
  shiftBar: {
    position: "absolute",
    height: 46,
    top: 0,
    borderRadius: 0,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 0,
    paddingVertical: 0,
    elevation: 3,
    borderWidth: 0,
  },
  shiftBarText: {
    color: "#000",
    fontSize: 11,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 1,
  },
  shiftTimeText: {
    color: "#000",
    fontSize: 10,
    fontWeight: "500",
    textAlign: "center",
  },
  infoCell: {
    padding: 0,
    justifyContent: "flex-start",
    height: 46,
    overflow: "hidden",
    backgroundColor: colors.surface,
  },
  infoContent: {
    marginBottom: 0,
    padding: 2,
    borderRadius: 6,
    marginHorizontal: 0,
    marginTop: 1,
    borderWidth: 1,
    borderColor: colors.success,
    backgroundColor: colors.selected,
  },
  infoText: {
    fontSize: 9,
    fontWeight: "bold",
    marginBottom: 1,
  },
  infoTimeText: {
    fontSize: 8,
    color: colors.text.primary,
    marginBottom: 0,
  },
  statusText: {
    fontSize: 7,
    fontWeight: "500",
    color: colors.text.secondary,
  },
  emptyCell: {
    height: 46,
    borderRightWidth: 1,
    borderRightColor: colors.border,
    position: "relative",
  },
  emptyInfoCell: {
    height: 46,
    backgroundColor: colors.surface,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  input: {
    height: 29,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 3,
    paddingHorizontal: 6,
    marginBottom: 10,
  },
  picker: {
    height: 32,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 3,
    marginBottom: 10,
  },
  saveButton: {
    backgroundColor: colors.success,
    borderRadius: 3,
    paddingVertical: 6,
    alignItems: "center",
  },
  closeButton: {
    marginTop: 6,
    paddingVertical: 6,
  },
  closeButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  classBar: {
    position: "absolute",
    backgroundColor: "#b0b0b0",
    borderRadius: 4,
    opacity: 0.85,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 1,
    zIndex: 3,
  },
  headerCostCellLeft: {
    justifyContent: "flex-start",
    alignItems: "center",
    padding: 6,
    backgroundColor: colors.surface,
    borderRadius: 3,
  },
  costLabel: {
    fontSize: 11,
    fontWeight: "bold",
    color: colors.primary,
  },
  monthCostContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  monthCostContainerLeft: {
    position: "absolute",
    left: 0,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  monthPickerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  pdfButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.selected,
    padding: 5,
    borderRadius: 5,
    marginRight: 5,
  },
  pdfButtonText: {
    marginLeft: 3,
    color: colors.primary,
    fontWeight: "bold",
  },
});

export default styles;
