import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  demoContainer: {
    backgroundColor: '#f8fafc',
    borderRadius: 16,
    padding: 24,
    marginBottom: 32,
  },
  demoSelector: {
    marginBottom: 24,
  },
  demoSelectorContent: {
    paddingHorizontal: 4,
  },
  demoViewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    marginHorizontal: 6,
    borderWidth: 2,
    borderColor: '#e2e8f0',
  },
  demoViewButtonActive: {
    backgroundColor: '#3b82f6',
    borderColor: '#3b82f6',
  },
  demoViewButtonText: {
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '600',
    color: '#1e293b',
  },
  demoViewButtonTextActive: {
    color: '#ffffff',
  },
  demoViewDetails: {
    marginBottom: 24,
  },
  demoViewTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: 8,
  },
  demoViewDescription: {
    fontSize: 16,
    color: '#64748b',
    lineHeight: 24,
    marginBottom: 16,
  },
  demoFeatureList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  demoFeatureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
    marginBottom: 8,
  },
  demoFeatureDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#3b82f6',
    marginRight: 8,
  },
  demoFeatureText: {
    fontSize: 14,
    color: '#475569',
    fontWeight: '500',
  },
  demoMockupContainer: {
    marginBottom: 24,
  },
  demoMockupDesktop: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  demoMockupMobile: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  demoMockupCalendar: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  demoMockupTablet: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  demoMockupGoogle: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  demoScreenshot: {
    width: '100%',
    height: 200,
  },
  demoTabletHeader: {
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    marginBottom: 12,
  },
  demoTabletGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  demoTabletColumn: {
    flex: 1,
    marginHorizontal: 4,
  },
  demoTabletShift: {
    height: 40,
    backgroundColor: '#3b82f6',
    borderRadius: 6,
    marginBottom: 8,
  },
  demoGoogleHeader: {
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    marginBottom: 12,
  },
  demoGoogleBody: {
    flexDirection: 'row',
    height: 160,
  },
  demoGoogleTimeAxis: {
    width: 60,
    marginRight: 16,
  },
  demoGoogleTime: {
    fontSize: 12,
    color: '#64748b',
    marginBottom: 16,
  },
  demoGoogleEvents: {
    flex: 1,
    position: 'relative',
  },
  demoGoogleEvent: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 32,
    backgroundColor: '#3b82f6',
    borderRadius: 4,
  },
  demoHeaderText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e293b',
    textAlign: 'center',
  },
  demoDayText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 8,
  },
  demoExperienceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3b82f6',
    paddingVertical: 16,
    borderRadius: 12,
  },
  demoExperienceButtonText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
});