import { StyleSheet } from "react-native";
import { colors } from "@/common/common-constants/ColorConstants";

export const useTaskDetailModalStyles = () => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.surface,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: "white",
      borderBottomWidth: 1,
      borderBottomColor: "#e0e0e0",
    },
    closeButton: {
      padding: 8,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text.primary,
      flex: 1,
      textAlign: "center",
      marginHorizontal: 16,
    },
    headerActions: {
      flexDirection: "row",
      gap: 8,
    },
    actionButton: {
      padding: 8,
    },
    tabBar: {
      flexDirection: "row",
      backgroundColor: "white",
      borderBottomWidth: 1,
      borderBottomColor: "#e0e0e0",
    },
    tabButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 12,
      gap: 4,
    },
    tabButtonActive: {
      backgroundColor: colors.primary,
    },
    tabButtonText: {
      fontSize: 12,
      color: colors.text.secondary,
      fontWeight: "500",
    },
    tabButtonTextActive: {
      color: "white",
      fontWeight: "600",
    },
    contentContainer: {
      flex: 1,
    },
    tabContent: {
      flex: 1,
      padding: 16,
    },
    section: {
      backgroundColor: "white",
      borderRadius: 8,
      padding: 16,
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text.primary,
      marginBottom: 16,
    },
    infoGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    infoCard: {
      flex: 1,
      minWidth: "45%",
      backgroundColor: "#f8f9fa",
      borderRadius: 8,
      padding: 12,
      alignItems: "center",
    },
    infoIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 8,
    },
    infoLabel: {
      fontSize: 12,
      color: colors.text.secondary,
      marginBottom: 4,
    },
    infoValue: {
      fontSize: 14,
      fontWeight: "bold",
      color: colors.text.primary,
      textAlign: "center",
    },
    description: {
      fontSize: 16,
      color: colors.text.secondary,
      lineHeight: 24,
    },
    timeRestriction: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: "#fff3e0",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
    },
    timeRestrictionText: {
      fontSize: 16,
      color: "#e65100",
      fontWeight: "600",
    },
    tagsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    tag: {
      backgroundColor: colors.selected,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    tagText: {
      fontSize: 14,
      color: colors.primary,
      fontWeight: "500",
    },
    validityContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: "#fff3e0",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
    },
    validityText: {
      fontSize: 16,
      color: "#e65100",
      fontWeight: "600",
    },
    statusContainer: {
      alignItems: "flex-start",
    },
    statusBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
    },
    statusText: {
      color: "white",
      fontSize: 16,
      fontWeight: "600",
    },
    manualHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    editButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 6,
      backgroundColor: colors.surface,
    },
    editButtonText: {
      fontSize: 14,
      color: colors.text.secondary,
      fontWeight: "500",
    },
    manualInput: {
      borderWidth: 1,
      borderColor: "#e0e0e0",
      borderRadius: 8,
      padding: 16,
      fontSize: 16,
      minHeight: 200,
      backgroundColor: "white",
      textAlignVertical: "top",
    },
    manualActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 12,
      marginTop: 12,
    },
    cancelButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 6,
      backgroundColor: colors.surface,
    },
    cancelButtonText: {
      color: colors.text.secondary,
      fontWeight: "600",
    },
    saveButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 6,
      backgroundColor: colors.primary,
    },
    saveButtonText: {
      color: "white",
      fontWeight: "600",
    },
    manualContent: {
      minHeight: 200,
    },
    manualText: {
      fontSize: 16,
      color: colors.text.primary,
      lineHeight: 24,
    },
    emptyManual: {
      alignItems: "center",
      paddingVertical: 40,
    },
    emptyManualText: {
      fontSize: 18,
      color: colors.text.secondary,
      marginTop: 16,
      marginBottom: 8,
    },
    emptyManualSubtext: {
      fontSize: 14,
      color: colors.text.disabled,
      textAlign: "center",
      lineHeight: 20,
    },
    statsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    statCard: {
      flex: 1,
      minWidth: "45%",
      backgroundColor: "#f8f9fa",
      borderRadius: 8,
      padding: 16,
      alignItems: "center",
    },
    statValue: {
      fontSize: 24,
      fontWeight: "bold",
      color: colors.primary,
      marginBottom: 4,
    },
    statLabel: {
      fontSize: 12,
      color: colors.text.secondary,
    },
    performanceCard: {
      backgroundColor: "#f8f9fa",
      borderRadius: 8,
      padding: 12,
      marginBottom: 8,
    },
    performanceHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    performanceUser: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text.primary,
    },
    performanceLevel: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
    },
    performanceLevelText: {
      color: "white",
      fontSize: 12,
      fontWeight: "bold",
    },
    performanceStats: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    performanceStat: {
      fontSize: 14,
      color: colors.text.secondary,
    },
    emptyPerformance: {
      alignItems: "center",
      paddingVertical: 80,
    },
    emptyPerformanceText: {
      fontSize: 18,
      color: colors.text.secondary,
      marginTop: 16,
      marginBottom: 8,
    },
    emptyPerformanceSubtext: {
      fontSize: 14,
      color: colors.text.disabled,
      textAlign: "center",
      lineHeight: 20,
    },
    historyItem: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: 16,
    },
    historyIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surface,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    historyContent: {
      flex: 1,
    },
    historyAction: {
      fontSize: 16,
      color: colors.text.primary,
      marginBottom: 4,
    },
    historyDate: {
      fontSize: 14,
      color: colors.text.secondary,
    },
  });
};
