import { StyleSheet } from "react-native";
import { colors } from "@/common/common-constants/ColorConstants";

export const useTaskCreateModalStyles = () => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.surface,
      alignItems: "center",
    },
    modalContent: {
      flex: 1,
      width: "100%",
    },
    modalContentDesktop: {
      width: "70%",
      maxWidth: 1000,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: "white",
      borderBottomWidth: 1,
      borderBottomColor: "#e0e0e0",
    },
    closeButton: {
      padding: 8,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text.primary,
    },
    saveButton: {
      backgroundColor: colors.primary,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 6,
    },
    saveButtonDisabled: {
      backgroundColor: colors.text.disabled,
    },
    saveButtonText: {
      color: "white",
      fontWeight: "600",
    },
    content: {
      flex: 1,
      paddingHorizontal: 16,
    },
    section: {
      backgroundColor: "white",
      borderRadius: 8,
      padding: 16,
      marginVertical: 8,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text.primary,
      marginBottom: 12,
    },
    field: {
      marginBottom: 16,
    },
    fieldRow: {
      flexDirection: "row",
      gap: 12,
    },
    fieldLabel: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text.primary,
      marginBottom: 8,
    },
    fieldHelper: {
      fontSize: 12,
      color: colors.text.secondary,
      marginTop: 4,
      fontStyle: "italic",
    },
    textInput: {
      borderWidth: 1,
      borderColor: "#e0e0e0",
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 16,
      backgroundColor: "white",
    },
    errorInput: {
      borderWidth: 1,
      borderColor: "#f44336",
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 16,
      backgroundColor: "#fff5f5",
    },
    errorText: {
      fontSize: 12,
      color: "#f44336",
      marginTop: 4,
      fontStyle: "italic",
    },
    characterCounter: {
      fontSize: 12,
      color: "#666",
      textAlign: "right",
      marginTop: 4,
    },
    characterCounterError: {
      fontSize: 12,
      color: "#f44336",
      textAlign: "right",
      marginTop: 4,
      fontWeight: "bold",
    },
    textArea: {
      height: 80,
      textAlignVertical: "top",
    },
    optionsGrid: {
      flexDirection: "column",
      gap: 6,
      maxHeight: 300,
    },
    optionsRow: {
      flexDirection: "row",
      gap: 8,
    },
    optionChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    optionChipSelected: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    optionChipText: {
      fontSize: 14,
      color: colors.text.secondary,
    },
    optionChipTextSelected: {
      color: "white",
      fontWeight: "600",
    },
    levelChip: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 16,
      borderWidth: 2,
      backgroundColor: "white",
    },
    levelChipText: {
      fontSize: 14,
      fontWeight: "600",
    },
    dateButton: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#e0e0e0",
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 12,
      backgroundColor: "white",
    },
    dateButtonText: {
      fontSize: 16,
      color: colors.text.primary,
    },
    switchRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    switchLabel: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text.primary,
    },
    colorChip: {
      width: 40,
      height: 40,
      borderRadius: 20,
      margin: 4,
      borderWidth: 2,
      borderColor: "transparent",
      justifyContent: "center",
      alignItems: "center",
    },
    colorChipSelected: {
      borderColor: "#333",
      borderWidth: 3,
    },
    iconChip: {
      width: 50,
      height: 50,
      borderRadius: 8,
      margin: 4,
      borderWidth: 2,
      borderColor: "#ddd",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "white",
    },
    iconChipSelected: {
      borderColor: colors.primary,
      backgroundColor: "#f3f8ff",
    },
    iconChipText: {
      fontSize: 10,
      color: "#666",
      textAlign: "center",
      marginTop: 2,
    },
    optionContainer: {
      marginBottom: 12,
      width: "100%",
    },
    optionDescription: {
      fontSize: 12,
      color: colors.text.secondary,
      marginTop: 4,
      paddingHorizontal: 4,
      lineHeight: 16,
    },
    colorGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      justifyContent: "flex-start",
    },
    iconGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      justifyContent: "flex-start",
    },
    timeRangeContainer: {
      borderWidth: 1,
      borderColor: "#e0e0e0",
      borderRadius: 8,
      padding: 12,
      marginBottom: 8,
      backgroundColor: "#f9f9f9",
    },
    timeRangeHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    removeTimeRangeButton: {
      padding: 4,
      borderRadius: 4,
      backgroundColor: "#ffebee",
    },
    addTimeRangeButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: "#2196F3",
      borderStyle: "dashed",
      borderRadius: 8,
      backgroundColor: "#f3f8ff",
      marginTop: 8,
    },
    addTimeRangeText: {
      fontSize: 14,
      color: "#2196F3",
      fontWeight: "600",
      marginLeft: 4,
    },
  });
};
